### ISSUE TITLE
Can't load libclang on Debian

### ISSUE THREAD

**Issue by CJ-Johnson** [tjfontaine/node-ffi-generate#4]
I got ffi-generate working on my laptop with OS X. It was a bit of a pain, but I was able to confirm that it worked. Now, when I try to do it in Debian I can't for the life of me get it working. I keep getting the "Unable to load libclang, make sure you have 3.2 installed, either specify -L or have llvm-config in your path" error. I would really appreciate some guidance on this. Alternatively, can you update ffi-generate where it downloads libclang automatically so it knows where to find it?

Please respond!

CJ

**Comment by bletual** [comment]
Hi,

I had the same problem and I solved it :+1: 

sudo npm install -g ffi-generate

should be your LAST action before using "ffi-generate"

Regards.

**Comment by noth8** [comment]
#3
